---
development:
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/dev.db
  # Application
  API_HOST: http://localhost:9090

test:
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db
  # Application
  API_HOST: http://localhost:9090

production:
  API_HOST: http://drinkking-api.herokuapp.com/
