# API testing workflow config for CI/CD on Github

name: API continuous integration

on:
  push:
    branches: [master]

  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  api_test:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database
        run: RACK_ENV=test bundle exec rake db:migrate

      - name: Run all specs
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          EXTRACT_QUEUE_URL: ${{ secrets.EXTRACT_QUEUE_URL }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          rake worker:run:test &
          bundle exec rake spec
